base: acoustic/ru_en.yaml

_general_:
  device: cuda:0
  seed: 23

  _dirname_: /content/results
  _label_: voice_ru_en  # name for the experiment

  resume_from_checkpoint: /content/acoustic_en_ipa.pt
  warm_start: true
  finetune_layers: []


dataset:
  root: /content/dataset  # or change to any other path

  _train_:
    meta_name: meta_train.csv  # training metadata path relative to the dataset root

  _eval_:
    meta_name: meta_valid.csv  # validation metadata path relative to the dataset root


model:
  encoder:
    transformer_layer:
      attention:
        dropout: 0.3
      feed_forward:
        dropout: 0.3


trainer:
  epochs: 50
  batch_size: 24
  eval_batch_size: 48

  eval_strategy: steps
  eval_steps: 50

  num_workers: 2

  project_name: isp-tts  # wandb project name
  accelerator:
    log_with: [tensorboard]
#    log_with: [wandb, tensorboard]
  tracker_kwargs:
    tensorboard: {}
    wandb:
      name: ${version:}/${date:}/${_general_._label_}

  optimization:
    optimizer:
      lr: !!float 1e-4
    lr_scheduler:
      _target_: exponential
      gamma: 0.995

  save_rewrite_checkpoint: false